// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HwcBootstrapper.ConfigTemplates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\projects\dotnet-hwc\dotnet-hwc\ConfigTemplates\WebConfig.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class WebConfig : WebConfigBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<!-- the root web configuration file -->\r" +
                    "\n<configuration>\r\n    <!--\r\n        Using a location directive with a missing pa" +
                    "th attribute\r\n        scopes the configuration to the entire machine.  If used i" +
                    "n\r\n        conjunction with allowOverride=\"false\", it can be used to\r\n        pr" +
                    "event configuration from being altered on the machine\r\n\r\n        Administrators " +
                    "that want to restrict permissions granted to\r\n        web applications should ch" +
                    "ange the default Trust level and ensure\r\n        that overrides are not allowed\r" +
                    "\n    -->\r\n    <location allowOverride=\"true\">\r\n        <system.web>\r\n           " +
                    " <securityPolicy>\r\n                <trustLevel name=\"Full\" policyFile=\"internal\"" +
                    " />\r\n                <trustLevel name=\"High\" policyFile=\"web_hightrust.config\" /" +
                    ">\r\n                <trustLevel name=\"Medium\" policyFile=\"web_mediumtrust.config\"" +
                    " />\r\n                <trustLevel name=\"Low\"  policyFile=\"web_lowtrust.config\" />" +
                    "\r\n                <trustLevel name=\"Minimal\" policyFile=\"web_minimaltrust.config" +
                    "\" />\r\n            </securityPolicy>\r\n            <trust level=\"Full\" originUrl=\"" +
                    "\" />\r\n            <fullTrustAssemblies>\r\n                <add\r\n                 " +
                    "   assemblyName=\"Microsoft.VisualStudio.Enterprise.AspNetHelper\"\r\n              " +
                    "      version=\"11.0.0.0\"\r\n                    publicKey=\"00240000048000009400000" +
                    "0060200000024000052534131000400000100010007D1FA57C4AED9F0A32E84AA0FAEFD0DE9E8FD6" +
                    "AEC8F87FB03766C834C99921EB23BE79AD9D5DCC1DD9AD236132102900B723CF980957FC4E177108" +
                    "FC607774F29E8320E92EA05ECE4E821C0A5EFE8F1645C4C0C93C1AB99285D622CAA652C1DFAD63D7" +
                    "45D6F2DE5F17E5EAF0FC4963D261C8A12436518206DC093344D5AD293\"\r\n                    " +
                    "/>\r\n                <add\r\n                    assemblyName=\"Microsoft.VisualStud" +
                    "io.Web\"\r\n                    version=\"11.0.0.0\"\r\n                    publicKey=\"" +
                    "002400000480000094000000060200000024000052534131000400000100010007D1FA57C4AED9F0" +
                    "A32E84AA0FAEFD0DE9E8FD6AEC8F87FB03766C834C99921EB23BE79AD9D5DCC1DD9AD23613210290" +
                    "0B723CF980957FC4E177108FC607774F29E8320E92EA05ECE4E821C0A5EFE8F1645C4C0C93C1AB99" +
                    "285D622CAA652C1DFAD63D745D6F2DE5F17E5EAF0FC4963D261C8A12436518206DC093344D5AD293" +
                    "\"\r\n                    />\r\n                <add\r\n                    assemblyNam" +
                    "e=\"Microsoft.Web.Infrastructure\"\r\n                    version=\"1.0.0.0\"\r\n       " +
                    "             publicKey=\"00240000048000009400000006020000002400005253413100040000" +
                    "01000100B5FC90E7027F67871E773A8FDE8938C81DD402BA65B9201D60593E96C492651E889CC13F" +
                    "1415EBB53FAC1131AE0BD333C5EE6021672D9718EA31A8AEBD0DA0072F25D87DBA6FC90FFD598ED4" +
                    "DA35E44C398C454307E8E33B8426143DAEC9F596836F97C8F74750E5975C64E2189F45DEF46B2A2B" +
                    "1247ADC3652BF5C308055DA9\"\r\n                    />\r\n                <add\r\n       " +
                    "             assemblyName=\"System.Data.SqlServerCe\"\r\n                    version" +
                    "=\"4.0.0.0\"\r\n                    publicKey=\"0024000004800000940000000602000000240" +
                    "000525341310004000001000100272736ad6e5f9586bac2d531eabc3acc666c2f8ec879fa94f8f7b" +
                    "0327d2ff2ed523448f83c3d5c5dd2dfc7bc99c5286b2c125117bf5cbe242b9d41750732b2bdffe64" +
                    "9c6efb8e5526d526fdd130095ecdb7bf210809c6cdad8824faa9ac0310ac3cba2aa0523567b2dfa7" +
                    "fe250b30facbd62d4ec99b94ac47c7d3b28f1f6e4c8\"\r\n                    />\r\n          " +
                    "  </fullTrustAssemblies>\r\n            <partialTrustVisibleAssemblies />\r\n       " +
                    " </system.web>\r\n    </location>\r\n\r\n    <system.codedom>\r\n        <compilers>\r\n  " +
                    "          <compiler language=\"c#;cs;csharp\" extension=\".cs\" warningLevel=\"4\" typ" +
                    "e=\"Microsoft.CSharp.CSharpCodeProvider, System, Version=4.0.0.0, Culture=neutral" +
                    ", PublicKeyToken=b77a5c561934e089\">\r\n                <providerOption name=\"Compi" +
                    "lerVersion\" value=\"v4.0\"/>\r\n                <providerOption name=\"WarnAsError\" v" +
                    "alue=\"false\"/>\r\n            </compiler>\r\n            <compiler language=\"vb;vbs;" +
                    "visualbasic;vbscript\" extension=\".vb\" warningLevel=\"4\" type=\"Microsoft.VisualBas" +
                    "ic.VBCodeProvider, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a" +
                    "5c561934e089\">\r\n                <providerOption name=\"CompilerVersion\" value=\"v4" +
                    ".0\"/>\r\n                <providerOption name=\"OptionInfer\" value=\"true\"/>\r\n      " +
                    "          <providerOption name=\"WarnAsError\" value=\"false\"/>\r\n            </comp" +
                    "iler>\r\n        </compilers>\r\n    </system.codedom>\r\n\r\n    <system.net>\r\n        " +
                    "<defaultProxy>\r\n            <proxy usesystemdefault=\"true\" />\r\n        </default" +
                    "Proxy>\r\n    </system.net>\r\n    <system.web>\r\n        <authorization>\r\n          " +
                    "  <allow users=\"*\" />\r\n        </authorization>\r\n\r\n        <browserCaps userAgen" +
                    "tCacheKeyLength=\"64\">\r\n            <result type=\"System.Web.Mobile.MobileCapabil" +
                    "ities, System.Web.Mobile, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5" +
                    "f7f11d50a3a\" />\r\n        </browserCaps>\r\n\r\n        <clientTarget>\r\n            <" +
                    "add alias=\"uplevel\" userAgent=\"Mozilla/5.0 (compatible; MSIE 6.0; Windows NT 5.1" +
                    ")\" />\r\n            <add alias=\"downlevel\" userAgent=\"Generic Downlevel\" />\r\n    " +
                    "    </clientTarget>\r\n\r\n        <compilation tempDirectory=\"");
            
            #line 88 "C:\projects\dotnet-hwc\dotnet-hwc\ConfigTemplates\WebConfig.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.TempDirectory));
            
            #line default
            #line hidden
            this.Write("\">\r\n            <assemblies>\r\n                <add assembly=\"mscorlib\" />\r\n      " +
                    "          <add assembly=\"Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, Pub" +
                    "licKeyToken=b03f5f7f11d50a3a\" />\r\n                <add assembly=\"System, Version" +
                    "=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\" />\r\n                " +
                    "<add assembly=\"System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKey" +
                    "Token=b03f5f7f11d50a3a\" />\r\n                <add assembly=\"System.Web, Version=4" +
                    ".0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />\r\n                <a" +
                    "dd assembly=\"System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5" +
                    "c561934e089\" />\r\n                <add assembly=\"System.Web.Services, Version=4.0" +
                    ".0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />\r\n                <add" +
                    " assembly=\"System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c56" +
                    "1934e089\" />\r\n                <add assembly=\"System.Drawing, Version=4.0.0.0, Cu" +
                    "lture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />\r\n                <add assembl" +
                    "y=\"System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b" +
                    "03f5f7f11d50a3a\" />\r\n                <add assembly=\"System.IdentityModel, Versio" +
                    "n=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\" />\r\n               " +
                    " <add assembly=\"System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, " +
                    "PublicKeyToken=b77a5c561934e089\" />\r\n                <add assembly=\"System.Servi" +
                    "ceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\" />\r\n" +
                    "                <add assembly=\"System.ServiceModel.Activation, Version=4.0.0.0, " +
                    "Culture=neutral, PublicKeyToken=31bf3856ad364e35\"/>\r\n                <add assemb" +
                    "ly=\"System.ServiceModel.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31" +
                    "bf3856ad364e35\"/>\r\n                <add assembly=\"System.Activities, Version=4.0" +
                    ".0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\"/>\r\n                <add " +
                    "assembly=\"System.ServiceModel.Activities, Version=4.0.0.0, Culture=neutral, Publ" +
                    "icKeyToken=31bf3856ad364e35\"/>\r\n                <add assembly=\"System.WorkflowSe" +
                    "rvices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\"/>\r\n  " +
                    "              <add assembly=\"System.Core, Version=4.0.0.0, Culture=neutral, Publ" +
                    "icKeyToken=b77a5c561934e089\" />\r\n                <add assembly=\"System.Web.Exten" +
                    "sions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\" />\r\n  " +
                    "              <add assembly=\"System.Data.DataSetExtensions, Version=4.0.0.0, Cul" +
                    "ture=neutral, PublicKeyToken=b77a5c561934e089\" />\r\n                <add assembly" +
                    "=\"System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934" +
                    "e089\" />\r\n                <add assembly=\"System.ComponentModel.DataAnnotations, " +
                    "Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\"/>\r\n          " +
                    "      <add assembly=\"System.Web.DynamicData, Version=4.0.0.0, Culture=neutral, P" +
                    "ublicKeyToken=31bf3856ad364e35\"/>\r\n                <add assembly=\"System.Web.App" +
                    "licationServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364" +
                    "e35\" />\r\n                <add assembly=\"*\" />\r\n            </assemblies>\r\n      " +
                    "      <buildProviders>\r\n                <add extension=\".aspx\" type=\"System.Web." +
                    "Compilation.PageBuildProvider\" />\r\n                <add extension=\".ascx\" type=\"" +
                    "System.Web.Compilation.UserControlBuildProvider\" />\r\n                <add extens" +
                    "ion=\".master\" type=\"System.Web.Compilation.MasterPageBuildProvider\" />\r\n        " +
                    "        <add extension=\".asmx\" type=\"System.Web.Compilation.WebServiceBuildProvi" +
                    "der\" />\r\n                <add extension=\".ashx\" type=\"System.Web.Compilation.Web" +
                    "HandlerBuildProvider\" />\r\n                <add extension=\".soap\" type=\"System.We" +
                    "b.Compilation.WebServiceBuildProvider\" />\r\n                <add extension=\".resx" +
                    "\" type=\"System.Web.Compilation.ResXBuildProvider\" />\r\n                <add exten" +
                    "sion=\".resources\" type=\"System.Web.Compilation.ResourcesBuildProvider\" />\r\n     " +
                    "           <add extension=\".wsdl\" type=\"System.Web.Compilation.WsdlBuildProvider" +
                    "\" />\r\n                <add extension=\".xsd\" type=\"System.Web.Compilation.XsdBuil" +
                    "dProvider\" />\r\n                <add extension=\".js\" type=\"System.Web.Compilation" +
                    ".ForceCopyBuildProvider\" />\r\n                <add extension=\".lic\" type=\"System." +
                    "Web.Compilation.IgnoreFileBuildProvider\" />\r\n                <add extension=\".li" +
                    "cx\" type=\"System.Web.Compilation.IgnoreFileBuildProvider\" />\r\n                <a" +
                    "dd extension=\".exclude\" type=\"System.Web.Compilation.IgnoreFileBuildProvider\" />" +
                    "\r\n                <add extension=\".refresh\" type=\"System.Web.Compilation.IgnoreF" +
                    "ileBuildProvider\" />\r\n                <add extension=\".edmx\" type=\"System.Data.E" +
                    "ntity.Design.AspNet.EntityDesignerBuildProvider\" />\r\n                <add extens" +
                    "ion=\".xoml\" type=\"System.ServiceModel.Activation.WorkflowServiceBuildProvider, S" +
                    "ystem.WorkflowServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf385" +
                    "6ad364e35\"/>\r\n                <add extension=\".svc\" type=\"System.ServiceModel.Ac" +
                    "tivation.ServiceBuildProvider, System.ServiceModel.Activation, Version=4.0.0.0, " +
                    "Culture=neutral, PublicKeyToken=31bf3856ad364e35\" />\r\n                <add exten" +
                    "sion=\".xamlx\" type=\"System.Xaml.Hosting.XamlBuildProvider, System.Xaml.Hosting, " +
                    "Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\" />\r\n         " +
                    "   </buildProviders>\r\n            <expressionBuilders>\r\n                <add exp" +
                    "ressionPrefix=\"Resources\" type=\"System.Web.Compilation.ResourceExpressionBuilder" +
                    "\" />\r\n                <add expressionPrefix=\"ConnectionStrings\" type=\"System.Web" +
                    ".Compilation.ConnectionStringsExpressionBuilder\" />\r\n                <add expres" +
                    "sionPrefix=\"AppSettings\" type=\"System.Web.Compilation.AppSettingsExpressionBuild" +
                    "er\" />\r\n                <add expressionPrefix=\"RouteUrl\" type=\"System.Web.Compil" +
                    "ation.RouteUrlExpressionBuilder\"/>\r\n                <add expressionPrefix=\"Route" +
                    "Value\" type=\"System.Web.Compilation.RouteValueExpressionBuilder\"/>\r\n            " +
                    "</expressionBuilders>\r\n            <folderLevelBuildProviders>\r\n                " +
                    "<add name=\"DataServiceBuildProvider\" type=\"System.Data.Services.BuildProvider.Da" +
                    "taServiceBuildProvider, System.Data.Services.Design, Version=4.0.0.0, Culture=ne" +
                    "utral, PublicKeyToken=b77a5c561934e089\"/>\r\n            </folderLevelBuildProvide" +
                    "rs>\r\n        </compilation>\r\n\r\n        <healthMonitoring>\r\n            <bufferMo" +
                    "des>\r\n                <add name=\"Critical Notification\" maxBufferSize=\"100\" maxF" +
                    "lushSize=\"20\"\r\n                    urgentFlushThreshold=\"1\" regularFlushInterval" +
                    "=\"Infinite\" urgentFlushInterval=\"00:01:00\"\r\n                    maxBufferThreads" +
                    "=\"1\" />\r\n                <add name=\"Notification\" maxBufferSize=\"300\" maxFlushSi" +
                    "ze=\"20\"\r\n                    urgentFlushThreshold=\"1\" regularFlushInterval=\"Infi" +
                    "nite\" urgentFlushInterval=\"00:01:00\"\r\n                    maxBufferThreads=\"1\" /" +
                    ">\r\n                <add name=\"Analysis\" maxBufferSize=\"1000\" maxFlushSize=\"100\"\r" +
                    "\n                    urgentFlushThreshold=\"100\" regularFlushInterval=\"00:05:00\"\r" +
                    "\n                    urgentFlushInterval=\"00:01:00\" maxBufferThreads=\"1\" />\r\n   " +
                    "             <add name=\"Logging\" maxBufferSize=\"1000\" maxFlushSize=\"200\" urgentF" +
                    "lushThreshold=\"800\"\r\n                    regularFlushInterval=\"00:30:00\" urgentF" +
                    "lushInterval=\"00:05:00\"\r\n                    maxBufferThreads=\"1\" />\r\n          " +
                    "  </bufferModes>\r\n\r\n            <providers>\r\n                <add name=\"EventLog" +
                    "Provider\" type=\"System.Web.Management.EventLogWebEventProvider,System.Web,Versio" +
                    "n=4.0.0.0,Culture=neutral,PublicKeyToken=b03f5f7f11d50a3a\" />\r\n                <" +
                    "add connectionStringName=\"LocalSqlServer\" maxEventDetailsLength=\"1073741823\"\r\n  " +
                    "                  buffer=\"false\" bufferMode=\"Notification\" name=\"SqlWebEventProv" +
                    "ider\"\r\n                    type=\"System.Web.Management.SqlWebEventProvider,Syste" +
                    "m.Web,Version=4.0.0.0,Culture=neutral,PublicKeyToken=b03f5f7f11d50a3a\" />\r\n     " +
                    "           <add name=\"WmiWebEventProvider\" type=\"System.Web.Management.WmiWebEve" +
                    "ntProvider,System.Web,Version=4.0.0.0,Culture=neutral,PublicKeyToken=b03f5f7f11d" +
                    "50a3a\" />\r\n            </providers>\r\n\r\n            <profiles>\r\n                <" +
                    "add name=\"Default\" minInstances=\"1\" maxLimit=\"Infinite\" minInterval=\"00:01:00\"\r\n" +
                    "                    custom=\"\" />\r\n                <add name=\"Critical\" minInstan" +
                    "ces=\"1\" maxLimit=\"Infinite\" minInterval=\"00:00:00\"\r\n                    custom=\"" +
                    "\" />\r\n            </profiles>\r\n\r\n            <rules>\r\n                <add name=" +
                    "\"All Errors Default\" eventName=\"All Errors\" provider=\"EventLogProvider\"\r\n       " +
                    "             profile=\"Default\" minInstances=\"1\" maxLimit=\"Infinite\" minInterval=" +
                    "\"00:01:00\"\r\n                    custom=\"\" />\r\n                <add name=\"Failure" +
                    " Audits Default\" eventName=\"Failure Audits\"\r\n                    provider=\"Event" +
                    "LogProvider\" profile=\"Default\" minInstances=\"1\"\r\n                    maxLimit=\"I" +
                    "nfinite\" minInterval=\"00:01:00\" custom=\"\" />\r\n            </rules>\r\n\r\n          " +
                    "  <eventMappings>\r\n                <add name=\"All Events\" type=\"System.Web.Manag" +
                    "ement.WebBaseEvent,System.Web,Version=4.0.0.0,Culture=neutral,PublicKeyToken=b03" +
                    "f5f7f11d50a3a\"\r\n                    startEventCode=\"0\" endEventCode=\"2147483647\"" +
                    " />\r\n                <add name=\"Heartbeats\" type=\"System.Web.Management.WebHeart" +
                    "beatEvent,System.Web,Version=4.0.0.0,Culture=neutral,PublicKeyToken=b03f5f7f11d5" +
                    "0a3a\"\r\n                    startEventCode=\"0\" endEventCode=\"2147483647\" />\r\n    " +
                    "            <add name=\"Application Lifetime Events\" type=\"System.Web.Management." +
                    "WebApplicationLifetimeEvent,System.Web,Version=4.0.0.0,Culture=neutral,PublicKey" +
                    "Token=b03f5f7f11d50a3a\"\r\n                    startEventCode=\"0\" endEventCode=\"21" +
                    "47483647\" />\r\n                <add name=\"Request Processing Events\" type=\"System" +
                    ".Web.Management.WebRequestEvent,System.Web,Version=4.0.0.0,Culture=neutral,Publi" +
                    "cKeyToken=b03f5f7f11d50a3a\"\r\n                    startEventCode=\"0\" endEventCode" +
                    "=\"2147483647\" />\r\n                <add name=\"All Errors\" type=\"System.Web.Manage" +
                    "ment.WebBaseErrorEvent,System.Web,Version=4.0.0.0,Culture=neutral,PublicKeyToken" +
                    "=b03f5f7f11d50a3a\"\r\n                    startEventCode=\"0\" endEventCode=\"2147483" +
                    "647\" />\r\n                <add name=\"Infrastructure Errors\" type=\"System.Web.Mana" +
                    "gement.WebErrorEvent,System.Web,Version=4.0.0.0,Culture=neutral,PublicKeyToken=b" +
                    "03f5f7f11d50a3a\"\r\n                    startEventCode=\"0\" endEventCode=\"214748364" +
                    "7\" />\r\n                <add name=\"Request Processing Errors\" type=\"System.Web.Ma" +
                    "nagement.WebRequestErrorEvent,System.Web,Version=4.0.0.0,Culture=neutral,PublicK" +
                    "eyToken=b03f5f7f11d50a3a\"\r\n                    startEventCode=\"0\" endEventCode=\"" +
                    "2147483647\" />\r\n                <add name=\"All Audits\" type=\"System.Web.Manageme" +
                    "nt.WebAuditEvent,System.Web,Version=4.0.0.0,Culture=neutral,PublicKeyToken=b03f5" +
                    "f7f11d50a3a\"\r\n                    startEventCode=\"0\" endEventCode=\"2147483647\" /" +
                    ">\r\n                <add name=\"Failure Audits\" type=\"System.Web.Management.WebFai" +
                    "lureAuditEvent,System.Web,Version=4.0.0.0,Culture=neutral,PublicKeyToken=b03f5f7" +
                    "f11d50a3a\"\r\n                    startEventCode=\"0\" endEventCode=\"2147483647\" />\r" +
                    "\n                <add name=\"Success Audits\" type=\"System.Web.Management.WebSucce" +
                    "ssAuditEvent,System.Web,Version=4.0.0.0,Culture=neutral,PublicKeyToken=b03f5f7f1" +
                    "1d50a3a\"\r\n                    startEventCode=\"0\" endEventCode=\"2147483647\" />\r\n " +
                    "           </eventMappings>\r\n\r\n        </healthMonitoring>\r\n\r\n        <httpHandl" +
                    "ers>\r\n            <add path=\"eurl.axd\" verb=\"*\" type=\"System.Web.HttpNotFoundHan" +
                    "dler\" validate=\"True\" />\r\n            <add path=\"trace.axd\" verb=\"*\" type=\"Syste" +
                    "m.Web.Handlers.TraceHandler\" validate=\"True\" />\r\n            <add path=\"WebResou" +
                    "rce.axd\" verb=\"GET\" type=\"System.Web.Handlers.AssemblyResourceLoader\" validate=\"" +
                    "True\" />\r\n            <add verb=\"*\" path=\"*_AppService.axd\" type=\"System.Web.Scr" +
                    "ipt.Services.ScriptHandlerFactory, System.Web.Extensions, Version=4.0.0.0, Cultu" +
                    "re=neutral, PublicKeyToken=31bf3856ad364e35\" validate=\"False\" />\r\n            <a" +
                    "dd verb=\"GET,HEAD\" path=\"ScriptResource.axd\" type=\"System.Web.Handlers.ScriptRes" +
                    "ourceHandler, System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKey" +
                    "Token=31bf3856ad364e35\" validate=\"False\"/>\r\n            <add path=\"*.axd\" verb=\"" +
                    "*\" type=\"System.Web.HttpNotFoundHandler\" validate=\"True\" />\r\n            <add pa" +
                    "th=\"*.aspx\" verb=\"*\" type=\"System.Web.UI.PageHandlerFactory\" validate=\"True\" />\r" +
                    "\n            <add path=\"*.ashx\" verb=\"*\" type=\"System.Web.UI.SimpleHandlerFactor" +
                    "y\" validate=\"True\" />\r\n            <add path=\"*.asmx\" verb=\"*\" type=\"System.Web." +
                    "Script.Services.ScriptHandlerFactory, System.Web.Extensions, Version=4.0.0.0, Cu" +
                    "lture=neutral, PublicKeyToken=31bf3856ad364e35\" validate=\"False\" />\r\n           " +
                    " <add path=\"*.rem\" verb=\"*\" type=\"System.Runtime.Remoting.Channels.Http.HttpRemo" +
                    "tingHandlerFactory, System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, P" +
                    "ublicKeyToken=b77a5c561934e089\" validate=\"False\" />\r\n            <add path=\"*.so" +
                    "ap\" verb=\"*\" type=\"System.Runtime.Remoting.Channels.Http.HttpRemotingHandlerFact" +
                    "ory, System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b" +
                    "77a5c561934e089\" validate=\"False\" />\r\n            <add path=\"*.asax\" verb=\"*\" ty" +
                    "pe=\"System.Web.HttpForbiddenHandler\" validate=\"True\" />\r\n            <add path=\"" +
                    "*.ascx\" verb=\"*\" type=\"System.Web.HttpForbiddenHandler\" validate=\"True\" />\r\n    " +
                    "        <add path=\"*.master\" verb=\"*\" type=\"System.Web.HttpForbiddenHandler\" val" +
                    "idate=\"True\" />\r\n            <add path=\"*.skin\" verb=\"*\" type=\"System.Web.HttpFo" +
                    "rbiddenHandler\" validate=\"True\" />\r\n            <add path=\"*.browser\" verb=\"*\" t" +
                    "ype=\"System.Web.HttpForbiddenHandler\" validate=\"True\" />\r\n            <add path=" +
                    "\"*.sitemap\" verb=\"*\" type=\"System.Web.HttpForbiddenHandler\" validate=\"True\" />\r\n" +
                    "            <add path=\"*.dll.config\" verb=\"GET,HEAD\" type=\"System.Web.StaticFile" +
                    "Handler\" validate=\"True\" />\r\n            <add path=\"*.exe.config\" verb=\"GET,HEAD" +
                    "\" type=\"System.Web.StaticFileHandler\" validate=\"True\" />\r\n            <add path=" +
                    "\"*.config\" verb=\"*\" type=\"System.Web.HttpForbiddenHandler\" validate=\"True\" />\r\n " +
                    "           <add path=\"*.cs\" verb=\"*\" type=\"System.Web.HttpForbiddenHandler\" vali" +
                    "date=\"True\" />\r\n            <add path=\"*.csproj\" verb=\"*\" type=\"System.Web.HttpF" +
                    "orbiddenHandler\" validate=\"True\" />\r\n            <add path=\"*.vb\" verb=\"*\" type=" +
                    "\"System.Web.HttpForbiddenHandler\" validate=\"True\" />\r\n            <add path=\"*.v" +
                    "bproj\" verb=\"*\" type=\"System.Web.HttpForbiddenHandler\" validate=\"True\" />\r\n     " +
                    "       <add path=\"*.webinfo\" verb=\"*\" type=\"System.Web.HttpForbiddenHandler\" val" +
                    "idate=\"True\" />\r\n            <add path=\"*.licx\" verb=\"*\" type=\"System.Web.HttpFo" +
                    "rbiddenHandler\" validate=\"True\" />\r\n            <add path=\"*.resx\" verb=\"*\" type" +
                    "=\"System.Web.HttpForbiddenHandler\" validate=\"True\" />\r\n            <add path=\"*." +
                    "resources\" verb=\"*\" type=\"System.Web.HttpForbiddenHandler\" validate=\"True\" />\r\n " +
                    "           <add path=\"*.mdb\" verb=\"*\" type=\"System.Web.HttpForbiddenHandler\" val" +
                    "idate=\"True\" />\r\n            <add path=\"*.vjsproj\" verb=\"*\" type=\"System.Web.Htt" +
                    "pForbiddenHandler\" validate=\"True\" />\r\n            <add path=\"*.java\" verb=\"*\" t" +
                    "ype=\"System.Web.HttpForbiddenHandler\" validate=\"True\" />\r\n            <add path=" +
                    "\"*.jsl\" verb=\"*\" type=\"System.Web.HttpForbiddenHandler\" validate=\"True\" />\r\n    " +
                    "        <add path=\"*.ldb\" verb=\"*\" type=\"System.Web.HttpForbiddenHandler\"  valid" +
                    "ate=\"True\" />\r\n            <add path=\"*.ad\" verb=\"*\" type=\"System.Web.HttpForbid" +
                    "denHandler\" validate=\"True\" />\r\n            <add path=\"*.dd\" verb=\"*\" type=\"Syst" +
                    "em.Web.HttpForbiddenHandler\" validate=\"True\" />\r\n            <add path=\"*.ldd\" v" +
                    "erb=\"*\" type=\"System.Web.HttpForbiddenHandler\" validate=\"True\" />\r\n            <" +
                    "add path=\"*.sd\" verb=\"*\" type=\"System.Web.HttpForbiddenHandler\" validate=\"True\" " +
                    "/>\r\n            <add path=\"*.cd\" verb=\"*\" type=\"System.Web.HttpForbiddenHandler\"" +
                    " validate=\"True\" />\r\n            <add path=\"*.adprototype\" verb=\"*\" type=\"System" +
                    ".Web.HttpForbiddenHandler\" validate=\"True\" />\r\n            <add path=\"*.lddproto" +
                    "type\" verb=\"*\" type=\"System.Web.HttpForbiddenHandler\" validate=\"True\" />\r\n      " +
                    "      <add path=\"*.sdm\" verb=\"*\" type=\"System.Web.HttpForbiddenHandler\" validate" +
                    "=\"True\" />\r\n            <add path=\"*.sdmDocument\" verb=\"*\" type=\"System.Web.Http" +
                    "ForbiddenHandler\" validate=\"True\" />\r\n            <add path=\"*.mdf\" verb=\"*\" typ" +
                    "e=\"System.Web.HttpForbiddenHandler\" validate=\"True\" />\r\n            <add path=\"*" +
                    ".ldf\" verb=\"*\" type=\"System.Web.HttpForbiddenHandler\" validate=\"True\" />\r\n      " +
                    "      <add path=\"*.exclude\" verb=\"*\" type=\"System.Web.HttpForbiddenHandler\" vali" +
                    "date=\"True\" />\r\n            <add path=\"*.refresh\" verb=\"*\" type=\"System.Web.Http" +
                    "ForbiddenHandler\" validate=\"True\" />\r\n            <add path=\"*.svc\" verb=\"*\" typ" +
                    "e=\"System.ServiceModel.Activation.HttpHandler, System.ServiceModel.Activation, V" +
                    "ersion=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\" validate=\"Fals" +
                    "e\"/>\r\n            <add path=\"*.rules\" verb=\"*\" type=\"System.Web.HttpForbiddenHan" +
                    "dler\" validate=\"True\"/>\r\n            <add path=\"*.xoml\" verb=\"*\" type=\"System.Se" +
                    "rviceModel.Activation.HttpHandler, System.ServiceModel.Activation, Version=4.0.0" +
                    ".0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\" validate=\"False\"/>\r\n      " +
                    "      <add path=\"*.xamlx\" verb=\"*\" type=\"System.Xaml.Hosting.XamlHttpHandlerFact" +
                    "ory, System.Xaml.Hosting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3" +
                    "856ad364e35\" validate=\"False\"/>\r\n            <add path=\"*.aspq\" verb=\"*\" type=\"S" +
                    "ystem.Web.HttpForbiddenHandler\" validate=\"True\"/>\r\n            <add path=\"*.csht" +
                    "m\" verb=\"*\" type=\"System.Web.HttpForbiddenHandler\" validate=\"True\"/>\r\n          " +
                    "  <add path=\"*.cshtml\" verb=\"*\" type=\"System.Web.HttpForbiddenHandler\" validate=" +
                    "\"True\"/>\r\n            <add path=\"*.vbhtm\" verb=\"*\" type=\"System.Web.HttpForbidde" +
                    "nHandler\" validate=\"True\"/>\r\n            <add path=\"*.vbhtml\" verb=\"*\" type=\"Sys" +
                    "tem.Web.HttpForbiddenHandler\" validate=\"True\"/>\r\n            <add path=\"*\" verb=" +
                    "\"GET,HEAD,POST\" type=\"System.Web.DefaultHttpHandler\" validate=\"True\" />\r\n       " +
                    "     <add path=\"*\" verb=\"*\" type=\"System.Web.HttpMethodNotAllowedHandler\" valida" +
                    "te=\"True\" />\r\n        </httpHandlers>\r\n\r\n        <httpModules>\r\n            <add" +
                    " name=\"OutputCache\" type=\"System.Web.Caching.OutputCacheModule\" />\r\n            " +
                    "<add name=\"Session\" type=\"System.Web.SessionState.SessionStateModule\" />\r\n      " +
                    "      <add name=\"WindowsAuthentication\" type=\"System.Web.Security.WindowsAuthent" +
                    "icationModule\" />\r\n            <add name=\"FormsAuthentication\" type=\"System.Web." +
                    "Security.FormsAuthenticationModule\" />\r\n            <add name=\"PassportAuthentic" +
                    "ation\" type=\"System.Web.Security.PassportAuthenticationModule\" />\r\n            <" +
                    "add name=\"RoleManager\" type=\"System.Web.Security.RoleManagerModule\" />\r\n        " +
                    "    <add name=\"UrlAuthorization\" type=\"System.Web.Security.UrlAuthorizationModul" +
                    "e\" />\r\n            <add name=\"FileAuthorization\" type=\"System.Web.Security.FileA" +
                    "uthorizationModule\" />\r\n            <add name=\"AnonymousIdentification\" type=\"Sy" +
                    "stem.Web.Security.AnonymousIdentificationModule\" />\r\n            <add name=\"Prof" +
                    "ile\" type=\"System.Web.Profile.ProfileModule\" />\r\n            <add name=\"ErrorHan" +
                    "dlerModule\" type=\"System.Web.Mobile.ErrorHandlerModule, System.Web.Mobile, Versi" +
                    "on=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />\r\n            <a" +
                    "dd name=\"ServiceModel\" type=\"System.ServiceModel.Activation.HttpModule, System.S" +
                    "erviceModel.Activation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf385" +
                    "6ad364e35\" />\r\n            <add name=\"UrlRoutingModule-4.0\" type=\"System.Web.Rou" +
                    "ting.UrlRoutingModule\" />\r\n            <add name=\"ScriptModule-4.0\" type=\"System" +
                    ".Web.Handlers.ScriptModule, System.Web.Extensions, Version=4.0.0.0, Culture=neut" +
                    "ral, PublicKeyToken=31bf3856ad364e35\"/>\r\n        </httpModules>\r\n\r\n        <mobi" +
                    "leControls sessionStateHistorySize=\"6\" cookielessDataDictionaryType=\"System.Web." +
                    "Mobile.CookielessData\">\r\n            <device name=\"XhtmlDeviceAdapters\"\r\n       " +
                    "         predicateClass=\"System.Web.UI.MobileControls.Adapters.XhtmlAdapters.Xht" +
                    "mlPageAdapter\"\r\n                predicateMethod=\"DeviceQualifies\"\r\n             " +
                    "   pageAdapter=\"System.Web.UI.MobileControls.Adapters.XhtmlAdapters.XhtmlPageAda" +
                    "pter\">\r\n\r\n                <control name=\"System.Web.UI.MobileControls.Panel\"    " +
                    "         adapter=\"System.Web.UI.MobileControls.Adapters.XhtmlAdapters.XhtmlPanel" +
                    "Adapter\" />\r\n                <control name=\"System.Web.UI.MobileControls.Form\"  " +
                    "            adapter=\"System.Web.UI.MobileControls.Adapters.XhtmlAdapters.XhtmlFo" +
                    "rmAdapter\" />\r\n                <control name=\"System.Web.UI.MobileControls.TextB" +
                    "ox\"           adapter=\"System.Web.UI.MobileControls.Adapters.XhtmlAdapters.Xhtml" +
                    "TextBoxAdapter\" />\r\n                <control name=\"System.Web.UI.MobileControls." +
                    "Label\"             adapter=\"System.Web.UI.MobileControls.Adapters.XhtmlAdapters." +
                    "XhtmlLabelAdapter\" />\r\n                <control name=\"System.Web.UI.MobileContro" +
                    "ls.LiteralText\"       adapter=\"System.Web.UI.MobileControls.Adapters.XhtmlAdapte" +
                    "rs.XhtmlLiteralTextAdapter\" />\r\n                <control name=\"System.Web.UI.Mob" +
                    "ileControls.Link\"              adapter=\"System.Web.UI.MobileControls.Adapters.Xh" +
                    "tmlAdapters.XhtmlLinkAdapter\" />\r\n                <control name=\"System.Web.UI.M" +
                    "obileControls.Command\"           adapter=\"System.Web.UI.MobileControls.Adapters." +
                    "XhtmlAdapters.XhtmlCommandAdapter\" />\r\n                <control name=\"System.Web" +
                    ".UI.MobileControls.PhoneCall\"         adapter=\"System.Web.UI.MobileControls.Adap" +
                    "ters.XhtmlAdapters.XhtmlPhoneCallAdapter\" />\r\n                <control name=\"Sys" +
                    "tem.Web.UI.MobileControls.List\"              adapter=\"System.Web.UI.MobileContro" +
                    "ls.Adapters.XhtmlAdapters.XhtmlListAdapter\" />\r\n                <control name=\"S" +
                    "ystem.Web.UI.MobileControls.SelectionList\"     adapter=\"System.Web.UI.MobileCont" +
                    "rols.Adapters.XhtmlAdapters.XhtmlSelectionListAdapter\" />\r\n                <cont" +
                    "rol name=\"System.Web.UI.MobileControls.ObjectList\"        adapter=\"System.Web.UI" +
                    ".MobileControls.Adapters.XhtmlAdapters.XhtmlObjectListAdapter\" />\r\n             " +
                    "   <control name=\"System.Web.UI.MobileControls.Image\"             adapter=\"Syste" +
                    "m.Web.UI.MobileControls.Adapters.XhtmlAdapters.XhtmlImageAdapter\" />\r\n          " +
                    "      <control name=\"System.Web.UI.MobileControls.ValidationSummary\" adapter=\"Sy" +
                    "stem.Web.UI.MobileControls.Adapters.XhtmlAdapters.XhtmlValidationSummaryAdapter\"" +
                    " />\r\n                <control name=\"System.Web.UI.MobileControls.Calendar\"      " +
                    "    adapter=\"System.Web.UI.MobileControls.Adapters.XhtmlAdapters.XhtmlCalendarAd" +
                    "apter\" />\r\n                <control name=\"System.Web.UI.MobileControls.TextView\"" +
                    "          adapter=\"System.Web.UI.MobileControls.Adapters.XhtmlAdapters.XhtmlText" +
                    "ViewAdapter\" />\r\n                <control name=\"System.Web.UI.MobileControls.Mob" +
                    "ileControl\"     adapter=\"System.Web.UI.MobileControls.Adapters.XhtmlAdapters.Xht" +
                    "mlControlAdapter\" />\r\n                <control name=\"System.Web.UI.MobileControl" +
                    "s.BaseValidator\"     adapter=\"System.Web.UI.MobileControls.Adapters.XhtmlAdapter" +
                    "s.XhtmlValidatorAdapter\" />\r\n            </device>\r\n            <device name=\"Ht" +
                    "mlDeviceAdapters\"\r\n                predicateClass=\"System.Web.UI.MobileControls." +
                    "Adapters.HtmlPageAdapter\"\r\n                predicateMethod=\"DeviceQualifies\"\r\n  " +
                    "              pageAdapter=\"System.Web.UI.MobileControls.Adapters.HtmlPageAdapter" +
                    "\">\r\n\r\n                <control name=\"System.Web.UI.MobileControls.Panel\"        " +
                    "     adapter=\"System.Web.UI.MobileControls.Adapters.HtmlPanelAdapter\" />\r\n      " +
                    "          <control name=\"System.Web.UI.MobileControls.Form\"              adapter" +
                    "=\"System.Web.UI.MobileControls.Adapters.HtmlFormAdapter\" />\r\n                <co" +
                    "ntrol name=\"System.Web.UI.MobileControls.TextBox\"           adapter=\"System.Web." +
                    "UI.MobileControls.Adapters.HtmlTextBoxAdapter\" />\r\n                <control name" +
                    "=\"System.Web.UI.MobileControls.Label\"             adapter=\"System.Web.UI.MobileC" +
                    "ontrols.Adapters.HtmlLabelAdapter\" />\r\n                <control name=\"System.Web" +
                    ".UI.MobileControls.LiteralText\"       adapter=\"System.Web.UI.MobileControls.Adap" +
                    "ters.HtmlLiteralTextAdapter\" />\r\n                <control name=\"System.Web.UI.Mo" +
                    "bileControls.Link\"              adapter=\"System.Web.UI.MobileControls.Adapters.H" +
                    "tmlLinkAdapter\" />\r\n                <control name=\"System.Web.UI.MobileControls." +
                    "Command\"           adapter=\"System.Web.UI.MobileControls.Adapters.HtmlCommandAda" +
                    "pter\" />\r\n                <control name=\"System.Web.UI.MobileControls.PhoneCall\"" +
                    "         adapter=\"System.Web.UI.MobileControls.Adapters.HtmlPhoneCallAdapter\" />" +
                    "\r\n                <control name=\"System.Web.UI.MobileControls.List\"             " +
                    " adapter=\"System.Web.UI.MobileControls.Adapters.HtmlListAdapter\" />\r\n           " +
                    "     <control name=\"System.Web.UI.MobileControls.SelectionList\"     adapter=\"Sys" +
                    "tem.Web.UI.MobileControls.Adapters.HtmlSelectionListAdapter\" />\r\n               " +
                    " <control name=\"System.Web.UI.MobileControls.ObjectList\"        adapter=\"System." +
                    "Web.UI.MobileControls.Adapters.HtmlObjectListAdapter\" />\r\n                <contr" +
                    "ol name=\"System.Web.UI.MobileControls.Image\"             adapter=\"System.Web.UI." +
                    "MobileControls.Adapters.HtmlImageAdapter\" />\r\n                <control name=\"Sys" +
                    "tem.Web.UI.MobileControls.BaseValidator\"     adapter=\"System.Web.UI.MobileContro" +
                    "ls.Adapters.HtmlValidatorAdapter\" />\r\n                <control name=\"System.Web." +
                    "UI.MobileControls.ValidationSummary\" adapter=\"System.Web.UI.MobileControls.Adapt" +
                    "ers.HtmlValidationSummaryAdapter\" />\r\n                <control name=\"System.Web." +
                    "UI.MobileControls.Calendar\"          adapter=\"System.Web.UI.MobileControls.Adapt" +
                    "ers.HtmlCalendarAdapter\" />\r\n                <control name=\"System.Web.UI.Mobile" +
                    "Controls.TextView\"          adapter=\"System.Web.UI.MobileControls.Adapters.HtmlT" +
                    "extViewAdapter\" />\r\n                <control name=\"System.Web.UI.MobileControls." +
                    "MobileControl\"     adapter=\"System.Web.UI.MobileControls.Adapters.HtmlControlAda" +
                    "pter\" />\r\n            </device>\r\n            <device name=\"UpWmlDeviceAdapters\"\r" +
                    "\n                inheritsFrom=\"WmlDeviceAdapters\"\r\n                predicateClas" +
                    "s=\"System.Web.UI.MobileControls.Adapters.UpWmlPageAdapter\"\r\n                pred" +
                    "icateMethod=\"DeviceQualifies\"\r\n                pageAdapter=\"System.Web.UI.Mobile" +
                    "Controls.Adapters.UpWmlPageAdapter\">\r\n            </device>\r\n            <device" +
                    " name=\"WmlDeviceAdapters\"\r\n                predicateClass=\"System.Web.UI.MobileC" +
                    "ontrols.Adapters.WmlPageAdapter\"\r\n                predicateMethod=\"DeviceQualifi" +
                    "es\"\r\n                pageAdapter=\"System.Web.UI.MobileControls.Adapters.WmlPageA" +
                    "dapter\">\r\n\r\n                <control name=\"System.Web.UI.MobileControls.Panel\"  " +
                    "           adapter=\"System.Web.UI.MobileControls.Adapters.WmlPanelAdapter\" />\r\n " +
                    "               <control name=\"System.Web.UI.MobileControls.Form\"              ad" +
                    "apter=\"System.Web.UI.MobileControls.Adapters.WmlFormAdapter\" />\r\n               " +
                    " <control name=\"System.Web.UI.MobileControls.TextBox\"           adapter=\"System." +
                    "Web.UI.MobileControls.Adapters.WmlTextBoxAdapter\" />\r\n                <control n" +
                    "ame=\"System.Web.UI.MobileControls.Label\"             adapter=\"System.Web.UI.Mobi" +
                    "leControls.Adapters.WmlLabelAdapter\" />\r\n                <control name=\"System.W" +
                    "eb.UI.MobileControls.LiteralText\"       adapter=\"System.Web.UI.MobileControls.Ad" +
                    "apters.WmlLiteralTextAdapter\" />\r\n                <control name=\"System.Web.UI.M" +
                    "obileControls.Link\"              adapter=\"System.Web.UI.MobileControls.Adapters." +
                    "WmlLinkAdapter\" />\r\n                <control name=\"System.Web.UI.MobileControls." +
                    "Command\"           adapter=\"System.Web.UI.MobileControls.Adapters.WmlCommandAdap" +
                    "ter\" />\r\n                <control name=\"System.Web.UI.MobileControls.PhoneCall\" " +
                    "        adapter=\"System.Web.UI.MobileControls.Adapters.WmlPhoneCallAdapter\" />\r\n" +
                    "                <control name=\"System.Web.UI.MobileControls.List\"              a" +
                    "dapter=\"System.Web.UI.MobileControls.Adapters.WmlListAdapter\" />\r\n              " +
                    "  <control name=\"System.Web.UI.MobileControls.SelectionList\"     adapter=\"System" +
                    ".Web.UI.MobileControls.Adapters.WmlSelectionListAdapter\" />\r\n                <co" +
                    "ntrol name=\"System.Web.UI.MobileControls.ObjectList\"        adapter=\"System.Web." +
                    "UI.MobileControls.Adapters.WmlObjectListAdapter\" />\r\n                <control na" +
                    "me=\"System.Web.UI.MobileControls.Image\"             adapter=\"System.Web.UI.Mobil" +
                    "eControls.Adapters.WmlImageAdapter\" />\r\n                <control name=\"System.We" +
                    "b.UI.MobileControls.BaseValidator\"     adapter=\"System.Web.UI.MobileControls.Ada" +
                    "pters.WmlValidatorAdapter\" />\r\n                <control name=\"System.Web.UI.Mobi" +
                    "leControls.ValidationSummary\" adapter=\"System.Web.UI.MobileControls.Adapters.Wml" +
                    "ValidationSummaryAdapter\" />\r\n                <control name=\"System.Web.UI.Mobil" +
                    "eControls.Calendar\"          adapter=\"System.Web.UI.MobileControls.Adapters.WmlC" +
                    "alendarAdapter\" />\r\n                <control name=\"System.Web.UI.MobileControls." +
                    "TextView\"          adapter=\"System.Web.UI.MobileControls.Adapters.WmlTextViewAda" +
                    "pter\" />\r\n                <control name=\"System.Web.UI.MobileControls.MobileCont" +
                    "rol\"     adapter=\"System.Web.UI.MobileControls.Adapters.WmlControlAdapter\" />\r\n " +
                    "           </device>\r\n            <device name=\"ChtmlDeviceAdapters\"\r\n          " +
                    "      inheritsFrom=\"HtmlDeviceAdapters\"\r\n                predicateClass=\"System." +
                    "Web.UI.MobileControls.Adapters.ChtmlPageAdapter\"\r\n                predicateMetho" +
                    "d=\"DeviceQualifies\"\r\n                pageAdapter=\"System.Web.UI.MobileControls.A" +
                    "dapters.ChtmlPageAdapter\">\r\n\r\n                <control name=\"System.Web.UI.Mobil" +
                    "eControls.Form\"              adapter=\"System.Web.UI.MobileControls.Adapters.Chtm" +
                    "lFormAdapter\" />\r\n                <control name=\"System.Web.UI.MobileControls.Ca" +
                    "lendar\"          adapter=\"System.Web.UI.MobileControls.Adapters.ChtmlCalendarAda" +
                    "pter\" />\r\n                <control name=\"System.Web.UI.MobileControls.Image\"    " +
                    "         adapter=\"System.Web.UI.MobileControls.Adapters.ChtmlImageAdapter\" />\r\n " +
                    "               <control name=\"System.Web.UI.MobileControls.TextBox\"           ad" +
                    "apter=\"System.Web.UI.MobileControls.Adapters.ChtmlTextBoxAdapter\" />\r\n          " +
                    "      <control name=\"System.Web.UI.MobileControls.SelectionList\"     adapter=\"Sy" +
                    "stem.Web.UI.MobileControls.Adapters.ChtmlSelectionListAdapter\" />\r\n             " +
                    "   <control name=\"System.Web.UI.MobileControls.Command\"           adapter=\"Syste" +
                    "m.Web.UI.MobileControls.Adapters.ChtmlCommandAdapter\" />\r\n                <contr" +
                    "ol name=\"System.Web.UI.MobileControls.PhoneCall\"         adapter=\"System.Web.UI." +
                    "MobileControls.Adapters.ChtmlPhoneCallAdapter\" />\r\n                <control name" +
                    "=\"System.Web.UI.MobileControls.Link\"              adapter=\"System.Web.UI.MobileC" +
                    "ontrols.Adapters.ChtmlLinkAdapter\" />\r\n            </device>\r\n        </mobileCo" +
                    "ntrols>\r\n\r\n        <pages>\r\n            <namespaces>\r\n                <add names" +
                    "pace=\"System\" />\r\n                <add namespace=\"System.Collections\" />\r\n      " +
                    "          <add namespace=\"System.Collections.Generic\" />\r\n                <add n" +
                    "amespace=\"System.Collections.Specialized\" />\r\n                <add namespace=\"Sy" +
                    "stem.ComponentModel.DataAnnotations\" />\r\n                <add namespace=\"System." +
                    "Configuration\" />\r\n                <add namespace=\"System.Linq\" />\r\n            " +
                    "    <add namespace=\"System.Text\" />\r\n                <add namespace=\"System.Text" +
                    ".RegularExpressions\" />\r\n                <add namespace=\"System.Web\" />\r\n       " +
                    "         <add namespace=\"System.Web.Caching\" />\r\n                <add namespace=" +
                    "\"System.Web.DynamicData\" />\r\n                <add namespace=\"System.Web.SessionS" +
                    "tate\" />\r\n                <add namespace=\"System.Web.Security\" />\r\n             " +
                    "   <add namespace=\"System.Web.Profile\" />\r\n                <add namespace=\"Syste" +
                    "m.Web.UI\" />\r\n                <add namespace=\"System.Web.UI.WebControls\" />\r\n   " +
                    "             <add namespace=\"System.Web.UI.WebControls.WebParts\" />\r\n           " +
                    "     <add namespace=\"System.Web.UI.HtmlControls\" />\r\n                <add namesp" +
                    "ace=\"System.Xml.Linq\" />\r\n            </namespaces>\r\n\r\n            <controls>\r\n " +
                    "               <add tagPrefix=\"asp\" namespace=\"System.Web.UI.WebControls.WebPart" +
                    "s\" assembly=\"System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f" +
                    "7f11d50a3a\" />\r\n                <add tagPrefix=\"asp\" namespace=\"System.Web.UI\" a" +
                    "ssembly=\"System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken" +
                    "=31bf3856ad364e35\"/>\r\n                <add tagPrefix=\"asp\" namespace=\"System.Web" +
                    ".UI.WebControls\" assembly=\"System.Web.Extensions, Version=4.0.0.0, Culture=neutr" +
                    "al, PublicKeyToken=31bf3856ad364e35\"/>\r\n                <add tagPrefix=\"asp\" nam" +
                    "espace=\"System.Web.UI.WebControls.Expressions\" assembly=\"System.Web.Extensions, " +
                    "Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\"/>\r\n          " +
                    "      <add tagPrefix=\"asp\" namespace=\"System.Web.DynamicData\" assembly=\"System.W" +
                    "eb.DynamicData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e3" +
                    "5\"/>\r\n                <add tagPrefix=\"asp\" namespace=\"System.Web.UI.WebControls\"" +
                    " assembly=\"System.Web.Entity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b" +
                    "77a5c561934e089\" />\r\n            </controls>\r\n        </pages>\r\n\r\n        <proto" +
                    "cols>\r\n            <add name=\"net.tcp\" processHandlerType=\"System.ServiceModel.W" +
                    "asHosting.TcpProcessProtocolHandler, System.ServiceModel.WasHosting, Version=4.0" +
                    ".0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\"\r\n                appDoma" +
                    "inHandlerType=\"System.ServiceModel.WasHosting.TcpAppDomainProtocolHandler, Syste" +
                    "m.ServiceModel.WasHosting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a" +
                    "5c561934e089\"\r\n                validate=\"false\" />\r\n            <add name=\"net.p" +
                    "ipe\" processHandlerType=\"System.ServiceModel.WasHosting.NamedPipeProcessProtocol" +
                    "Handler, System.ServiceModel.WasHosting, Version=4.0.0.0, Culture=neutral, Publi" +
                    "cKeyToken=b77a5c561934e089\"\r\n                appDomainHandlerType=\"System.Servic" +
                    "eModel.WasHosting.NamedPipeAppDomainProtocolHandler, System.ServiceModel.WasHost" +
                    "ing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\"\r\n       " +
                    "         validate=\"false\" />\r\n            <add name=\"net.msmq\" processHandlerTyp" +
                    "e=\"System.ServiceModel.WasHosting.MsmqProcessProtocolHandler, System.ServiceMode" +
                    "l.WasHosting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\"" +
                    "\r\n                appDomainHandlerType=\"System.ServiceModel.WasHosting.MsmqAppDo" +
                    "mainProtocolHandler, System.ServiceModel.WasHosting, Version=4.0.0.0, Culture=ne" +
                    "utral, PublicKeyToken=b77a5c561934e089\"\r\n                validate=\"false\" />\r\n  " +
                    "          <add name=\"msmq.formatname\" processHandlerType=\"System.ServiceModel.Wa" +
                    "sHosting.MsmqIntegrationProcessProtocolHandler, System.ServiceModel.WasHosting, " +
                    "Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\"\r\n            " +
                    "    appDomainHandlerType=\"System.ServiceModel.WasHosting.MsmqIntegrationAppDomai" +
                    "nProtocolHandler, System.ServiceModel.WasHosting, Version=4.0.0.0, Culture=neutr" +
                    "al, PublicKeyToken=b77a5c561934e089\"\r\n                validate=\"false\" />\r\n     " +
                    "   </protocols>\r\n\r\n        <siteMap>\r\n            <providers>\r\n                <" +
                    "add siteMapFile=\"web.sitemap\" name=\"AspNetXmlSiteMapProvider\"\r\n                 " +
                    "   type=\"System.Web.XmlSiteMapProvider, System.Web, Version=4.0.0.0, Culture=neu" +
                    "tral, PublicKeyToken=b03f5f7f11d50a3a\" />\r\n            </providers>\r\n        </s" +
                    "iteMap>\r\n\r\n        <urlMappings enabled=\"true\" />\r\n\r\n        <webControls client" +
                    "ScriptsLocation=\"/aspnet_client/{0}/{1}/\" />\r\n\r\n        <webParts>\r\n            " +
                    "<personalization>\r\n                <providers>\r\n                    <add connect" +
                    "ionStringName=\"LocalSqlServer\"\r\n                        name=\"AspNetSqlPersonali" +
                    "zationProvider\" type=\"System.Web.UI.WebControls.WebParts.SqlPersonalizationProvi" +
                    "der, System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a" +
                    "3a\" />\r\n                </providers>\r\n\r\n                <authorization>\r\n       " +
                    "             <deny users=\"*\" verbs=\"enterSharedScope\" />\r\n                    <a" +
                    "llow users=\"*\" verbs=\"modifyState\" />\r\n                </authorization>\r\n       " +
                    "     </personalization>\r\n\r\n            <transformers>\r\n                <add name" +
                    "=\"RowToFieldTransformer\" type=\"System.Web.UI.WebControls.WebParts.RowToFieldTran" +
                    "sformer\" />\r\n                <add name=\"RowToParametersTransformer\" type=\"System" +
                    ".Web.UI.WebControls.WebParts.RowToParametersTransformer\" />\r\n            </trans" +
                    "formers>\r\n        </webParts>\r\n    </system.web>\r\n    <system.serviceModel>\r\n   " +
                    "     <serviceHostingEnvironment>\r\n            <add name=\"net.tcp\" transportConfi" +
                    "gurationType=\"System.ServiceModel.Activation.TcpHostedTransportConfiguration, Sy" +
                    "stem.ServiceModel.Activation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=3" +
                    "1bf3856ad364e35\" />\r\n            <add name=\"net.pipe\" transportConfigurationType" +
                    "=\"System.ServiceModel.Activation.NamedPipeHostedTransportConfiguration, System.S" +
                    "erviceModel.Activation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf385" +
                    "6ad364e35\" />\r\n            <add name=\"net.msmq\" transportConfigurationType=\"Syst" +
                    "em.ServiceModel.Activation.MsmqHostedTransportConfiguration, System.ServiceModel" +
                    ".Activation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\" " +
                    "/>\r\n            <add name=\"msmq.formatname\" transportConfigurationType=\"System.S" +
                    "erviceModel.Activation.MsmqIntegrationHostedTransportConfiguration, System.Servi" +
                    "ceModel.Activation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad3" +
                    "64e35\" />\r\n        </serviceHostingEnvironment>\r\n    </system.serviceModel>\r\n   " +
                    " <system.xaml.hosting>\r\n        <httpHandlers>\r\n            <add xamlRootElement" +
                    "Type=\"System.ServiceModel.Activities.WorkflowService, System.ServiceModel.Activi" +
                    "ties, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\" httpHan" +
                    "dlerType=\"System.ServiceModel.Activities.Activation.ServiceModelActivitiesActiva" +
                    "tionHandlerAsync, System.ServiceModel.Activation, Version=4.0.0.0, Culture=neutr" +
                    "al, PublicKeyToken=31bf3856ad364e35\"/>\r\n            <add xamlRootElementType=\"Sy" +
                    "stem.Activities.Activity, System.Activities, Version=4.0.0.0, Culture=neutral, P" +
                    "ublicKeyToken=31bf3856ad364e35\" httpHandlerType=\"System.ServiceModel.Activities." +
                    "Activation.ServiceModelActivitiesActivationHandlerAsync, System.ServiceModel.Act" +
                    "ivation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\"/>\r\n " +
                    "       </httpHandlers>\r\n    </system.xaml.hosting>\r\n</configuration>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class WebConfigBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
